import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@ui/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex  items-center justify-center  h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
